import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Mail, Lock, User as UserIcon, Eye, EyeOff, ShieldCheck, KeyRound } from 'lucide-react';
import api from '../services/api.js';
import { useTranslation } from '../context/LanguageContext.tsx';

interface LoginProps {
  onLoginSuccess: (userData: any) => void;
  showToast: (message: string, type?: 'success' | 'error' | 'info' | 'warning') => void;
}

const Login: React.FC<LoginProps> = ({ onLoginSuccess, showToast }) => {
  const [isRegister, setIsRegister] = useState(false);
  const [isForgotPassword, setIsForgotPassword] = useState(false);
  const [is2FaStep, setIs2FaStep] = useState(false);
  
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [name, setName] = useState('');
  const [rememberMe, setRememberMe] = useState(false);
  const [showPassword, setShowPassword] = useState(false);
  const [twoFactorCode, setTwoFactorCode] = useState('');
  const [loading, setLoading] = useState(false);

  const navigate = useNavigate();
  const { t, language, setLanguage } = useTranslation();

  const handleAuth = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      if (isRegister) {
        // Register API call
        await api.post('/auth/register', { name, email, password });
        showToast(t('Registration successful! Please login.'), 'success');
        setIsRegister(false);
        setPassword('');
      } else {
        // Login API call
        const res = await api.post('/auth/login', { email, password, rememberMe });
        
        // Simulating checking 2FA trigger settings
        if (res.data.user.is_2fa_enabled) {
          setIs2FaStep(true);
          showToast(t('Please type your 2FA verification key.'), 'info');
        } else {
          onLoginSuccess(res.data.user);
          showToast(`${t('Welcome back')}, ${res.data.user.name}!`, 'success');
          navigate('/dashboard');
        }
      }
    } catch (err: any) {
      showToast(err.response?.data?.error || t('Authentication process encountered an error.'), 'error');
    } finally {
      setLoading(false);
    }
  };

  const handle2FaSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (twoFactorCode.trim().length === 6) {
      showToast(t('2FA verification check complete.'), 'success');
      api.get('/auth/me').then(res => {
        onLoginSuccess(res.data.user);
        navigate('/dashboard');
      });
    } else {
      showToast(t('Invalid verification key. Code must be 6 digits.'), 'error');
    }
  };

  const handleForgotSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    showToast(`${t('Password recovery guidelines sent to:')} ${email}`, 'success');
    setIsForgotPassword(false);
  };

  return (
    <div className="bg-gradient-welcome min-h-screen relative flex items-center justify-center p-6 text-slate-800 dark:text-slate-200">
      {/* Decorative glass elements */}
      <div className="absolute inset-0 pointer-events-none overflow-hidden z-0">
        <div className="absolute top-[10%] left-[20%] w-64 h-64 rounded-full bg-blue-500/10 dark:bg-blue-500/5 blur-[70px] float-slow"></div>
        <div className="absolute bottom-[20%] right-[20%] w-80 h-80 rounded-full bg-purple-500/10 dark:bg-purple-500/5 blur-[80px] float-slow" style={{ animationDelay: '-3s' }}></div>
      </div>

      <div className="relative z-10 w-full max-w-md glass-panel p-8 rounded-3xl shadow-2xl border border-white/50 dark:border-white/10 bg-white/70 dark:bg-slate-900/70">
        
        {/* Logo Branding */}
        <div className="flex flex-col items-center mb-6">
          <div className="w-12 h-12 rounded-2xl bg-gradient-to-tr from-blue-600 to-indigo-600 flex items-center justify-center text-white font-poppins font-bold text-2xl shadow-lg mb-2">
            E
          </div>
          <h1 className="font-poppins font-extrabold text-xl text-blue-600 dark:text-blue-400">{t('ELRAWDA')}</h1>
          <p className="text-[10px] text-slate-500 dark:text-slate-400 font-semibold tracking-wider uppercase -mt-0.5">{t('Wealth Management')}</p>
        </div>

        {/* 2FA STEP */}
        {is2FaStep ? (
          <form onSubmit={handle2FaSubmit} className="space-y-4">
            <h2 className="text-center font-bold text-base flex justify-center items-center gap-1.5">
              <ShieldCheck size={18} className="text-blue-600" />
              {t("Two-Factor Authentication")}
            </h2>
            <p className="text-xs text-slate-500 dark:text-slate-400 text-center leading-relaxed">
              {t("Enter the 6-digit verification code generated by your Authenticator app.")}
            </p>
            <div className="relative">
              <KeyRound className={`absolute ${language === 'ar' ? 'right-3' : 'left-3'} top-3 text-slate-400`} size={16} />
              <input
                required
                type="text"
                maxLength={6}
                placeholder="000 000"
                className="w-full py-2.5 rounded-xl border border-slate-300 dark:border-slate-700 bg-white/50 dark:bg-slate-950/20 text-sm focus:outline-none focus:border-blue-600 text-center tracking-[0.3em] font-bold"
                value={twoFactorCode}
                onChange={(e) => setTwoFactorCode(e.target.value.replace(/\D/g, ''))}
              />
            </div>
            <button
              type="submit"
              className="w-full py-2.5 rounded-xl bg-blue-600 hover:bg-blue-700 text-white font-semibold text-xs shadow-md transition-all flex justify-center"
            >
              {t("Verify Code")}
            </button>
            <button
              type="button"
              onClick={() => setIs2FaStep(false)}
              className="text-xs text-blue-600 dark:text-blue-400 block text-center hover:underline w-full mt-2"
            >
              {t("Back to Login")}
            </button>
          </form>
        ) : isForgotPassword ? (
          // FORGOT PASSWORD
          <form onSubmit={handleForgotSubmit} className="space-y-4">
            <h2 className="text-center font-bold text-base">{t("Recover Password")}</h2>
            <p className="text-xs text-slate-500 dark:text-slate-400 text-center leading-relaxed">
              {t("Provide your email, and we will send password reset coordinates.")}
            </p>
            <div className="relative">
              <Mail className={`absolute ${language === 'ar' ? 'right-3' : 'left-3'} top-3 text-slate-400`} size={16} />
              <input
                required
                type="email"
                placeholder={t("Email Address")}
                className={`w-full ${language === 'ar' ? 'pr-10 pl-4' : 'pl-10 pr-4'} py-2.5 rounded-xl border border-slate-300 dark:border-slate-700 bg-white/50 dark:bg-slate-950/20 text-sm focus:outline-none focus:border-blue-600`}
                value={email}
                onChange={(e) => setEmail(e.target.value)}
              />
            </div>
            <button
              type="submit"
              className="w-full py-2.5 rounded-xl bg-blue-600 hover:bg-blue-700 text-white font-semibold text-xs shadow-md transition-all"
            >
              {t("Send Reset Link")}
            </button>
            <button
              type="button"
              onClick={() => setIsForgotPassword(false)}
              className="text-xs text-blue-600 dark:text-blue-400 block text-center hover:underline w-full mt-2"
            >
              {t("Back to Login")}
            </button>
          </form>
        ) : (
          // LOGIN OR REGISTER FORM
          <form onSubmit={handleAuth} className="space-y-4">
            <h2 className="text-center font-poppins font-bold text-lg text-slate-800 dark:text-white">
              {isRegister ? t('Create Family Account') : t('Sign In to ELRAWDA')}
            </h2>
            <p className="text-xs text-slate-500 dark:text-slate-400 text-center leading-relaxed -mt-2">
              {!isRegister && t('Access the family wealth console')}
            </p>

            {isRegister && (
              <div className="relative">
                <UserIcon className={`absolute ${language === 'ar' ? 'right-3' : 'left-3'} top-3 text-slate-400`} size={16} />
                <input
                  required
                  type="text"
                  placeholder={t("Full Name")}
                  className={`w-full ${language === 'ar' ? 'pr-10 pl-4' : 'pl-10 pr-4'} py-2.5 rounded-xl border border-slate-300 dark:border-slate-700 bg-white/50 dark:bg-slate-955 text-sm focus:outline-none focus:border-blue-600`}
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                />
              </div>
            )}

            <div className="relative">
              <Mail className={`absolute ${language === 'ar' ? 'right-3' : 'left-3'} top-3 text-slate-400`} size={16} />
              <input
                required
                type="email"
                placeholder={t("Email Address")}
                className={`w-full ${language === 'ar' ? 'pr-10 pl-4' : 'pl-10 pr-4'} py-2.5 rounded-xl border border-slate-300 dark:border-slate-700 bg-white/50 dark:bg-slate-955 text-sm focus:outline-none focus:border-blue-600`}
                value={email}
                onChange={(e) => setEmail(e.target.value)}
              />
            </div>

            <div className="relative">
              <Lock className={`absolute ${language === 'ar' ? 'right-3' : 'left-3'} top-3 text-slate-400`} size={16} />
              <input
                required
                type={showPassword ? 'text' : 'password'}
                placeholder={t("Password")}
                className={`w-full ${language === 'ar' ? 'pr-10 pl-10' : 'pl-10 pr-10'} py-2.5 rounded-xl border border-slate-300 dark:border-slate-700 bg-white/50 dark:bg-slate-955 text-sm focus:outline-none focus:border-blue-600`}
                value={password}
                onChange={(e) => setPassword(e.target.value)}
              />
              <button
                type="button"
                className={`absolute ${language === 'ar' ? 'left-3' : 'right-3'} top-3 text-slate-400 hover:text-slate-650`}
                onClick={() => setShowPassword(!showPassword)}
              >
                {showPassword ? <EyeOff size={16} /> : <Eye size={16} />}
              </button>
            </div>

            {!isRegister && (
              <div className="flex justify-between items-center text-xs">
                <label className="flex items-center gap-1.5 cursor-pointer text-slate-505 dark:text-slate-400 font-medium">
                  <input
                    type="checkbox"
                    className="rounded border-slate-350 text-blue-600 focus:ring-0 focus:ring-offset-0 w-4 h-4 bg-transparent"
                    checked={rememberMe}
                    onChange={(e) => setRememberMe(e.target.checked)}
                  />
                  <span>{t("Remember this session")}</span>
                </label>
                <button
                  type="button"
                  onClick={() => setIsForgotPassword(true)}
                  className="text-blue-600 dark:text-blue-400 hover:underline"
                >
                  {t("Forgot Password?")}
                </button>
              </div>
            )}

            <button
              type="submit"
              disabled={loading}
              className="w-full py-3 rounded-xl bg-blue-600 hover:bg-blue-700 text-white font-semibold text-xs shadow-lg transition-all flex justify-center items-center font-poppins"
            >
              {loading ? (
                <span className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></span>
              ) : isRegister ? (
                t('Register & Setup')
              ) : (
                t('Sign In')
              )}
            </button>

            <div className="text-center text-xs mt-4">
              <span className="text-slate-400">
                {isRegister ? t('Already have an account? ') : t("Don't have a portfolio? ")}
              </span>
              <button
                type="button"
                onClick={() => setIsRegister(!isRegister)}
                className="text-blue-600 dark:text-blue-400 font-bold hover:underline"
              >
                {isRegister ? t('Login') : t('Get Started')}
              </button>
            </div>
          </form>
        )}
      </div>
    </div>
  );
};

export default Login;
