-- =========================================================================
-- ELRAWDA Migration: 002_schema.sql
-- Creates core tables: savings_goals, budgets, income, expenses, assets, debts, notifications, audit_logs
-- =========================================================================

-- 1. Savings Goals
CREATE TABLE IF NOT EXISTS public.savings_goals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  target DOUBLE PRECISION NOT NULL,
  current DOUBLE PRECISION DEFAULT 0.0,
  category TEXT NOT NULL,
  color TEXT DEFAULT 'blue',
  deadline TEXT NOT NULL,
  priority TEXT DEFAULT 'Medium',
  auto_contribution DOUBLE PRECISION DEFAULT 0.0,
  is_salary_deducted INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Budgets
CREATE TABLE IF NOT EXISTS public.budgets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  category TEXT NOT NULL,
  monthly_limit DOUBLE PRECISION NOT NULL,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, category)
);

-- 3. Income
CREATE TABLE IF NOT EXISTS public.income (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  amount DOUBLE PRECISION NOT NULL,
  source TEXT NOT NULL,
  category TEXT NOT NULL,
  date TEXT NOT NULL,
  recurring INT DEFAULT 0,
  interval TEXT,
  notes TEXT,
  attachment TEXT,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Expenses
CREATE TABLE IF NOT EXISTS public.expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  amount DOUBLE PRECISION NOT NULL,
  merchant TEXT NOT NULL,
  category TEXT NOT NULL,
  date TEXT NOT NULL,
  recurring INT DEFAULT 0,
  interval TEXT,
  tags TEXT,
  status TEXT DEFAULT 'Completed',
  notes TEXT,
  receipt TEXT,
  savings_goal_id BIGINT REFERENCES public.savings_goals(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Assets
CREATE TABLE IF NOT EXISTS public.assets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  value DOUBLE PRECISION NOT NULL,
  purchase_date TEXT NOT NULL,
  depreciation_rate DOUBLE PRECISION DEFAULT 0.0,
  recognized_type TEXT,
  metadata TEXT,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Debts
CREATE TABLE IF NOT EXISTS public.debts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  creditor TEXT NOT NULL,
  amount DOUBLE PRECISION NOT NULL,
  interest_rate DOUBLE PRECISION DEFAULT 0.0,
  monthly_payment DOUBLE PRECISION DEFAULT 0.0,
  due_date TEXT NOT NULL,
  status TEXT DEFAULT 'Active',
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Notifications
CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  message TEXT NOT NULL,
  is_read INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. Audit Logs
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  ip_address TEXT,
  user_agent TEXT,
  timestamp TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on all tables
ALTER TABLE public.savings_goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.budgets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.income ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.debts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- Define RLS Select/Insert/Update/Delete user partition policies
-- Users can only modify/read their own rows.

-- Savings Goals Policies
CREATE POLICY "Users can manage their own savings goals" ON public.savings_goals
  USING (auth.uid() = user_id);

-- Budgets Policies
CREATE POLICY "Users can manage their own budgets" ON public.budgets
  USING (auth.uid() = user_id);

-- Income Policies
CREATE POLICY "Users can manage their own income" ON public.income
  USING (auth.uid() = user_id);

-- Expenses Policies
CREATE POLICY "Users can manage their own expenses" ON public.expenses
  USING (auth.uid() = user_id);

-- Assets Policies
CREATE POLICY "Users can manage their own assets" ON public.assets
  USING (auth.uid() = user_id);

-- Debts Policies
CREATE POLICY "Users can manage their own debts" ON public.debts
  USING (auth.uid() = user_id);

-- Notifications Policies
CREATE POLICY "Users can manage their own notifications" ON public.notifications
  USING (auth.uid() = user_id);

-- Audit Logs Policies: Users can insert their own, view their own, or admin can view all
CREATE POLICY "Users can insert their own logs" ON public.audit_logs
  FOR INSERT WITH CHECK (auth.uid() = user_id OR user_id IS NULL);

CREATE POLICY "Users and admins can view logs" ON public.audit_logs
  FOR SELECT USING (
    auth.uid() = user_id 
    OR EXISTS (
      SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'
    )
  );
